title: "GitHubPages勉強会"

lang: ja
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

locale: ja_JP
title_separator: "|"
minimal_mistakes_skin: "air" # 全体の色合い

breadcrumbs: true
logo: "/assets/images/logo-150.png"
include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      header:
        overlay_image: /assets/images/header.png
        overlay_filter: 0.5
  # pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      author: default

theme: jekyll-theme-slate